### ISSUE TITLE
feat: add restrictions to page and itemsPerPage

### ISSUE THREAD

**Issue by lrstanley** [ariga/ogent#105]
I'm not sure if this is an ogent thing, or an ogen thing, however it would be nice if `page` and `itemsPerPage` were sanitized to be `> 1` and `< math.MaxInt32`, or handled as a bad request. Right now, if the integer for either is below 1, or above the maximum integer size, it will throw an error, which requires intercepting, validating which error it is, and responding accordingly. Because this would be required for every implementation using `ogent`, feel like it should be implemented here.

**Comment by masseelch** [comment]
This is done via #195
