### ISSUE TITLE
Package `syncint64` is deprecated

### ISSUE THREAD

**Issue by giovanni-orciuolo** [ariga/ogent#209]
The OpenTelemetry configuration generates the following imports:

```
import (
	"net/http"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/instrument/syncint64"
	"go.opentelemetry.io/otel/trace"

	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/otelogen"
)
```

The package `go.opentelemetry.io/otel/metric/instrument/syncint64`, however, is deprecated: https://pkg.go.dev/go.opentelemetry.io/otel/metric/instrument/syncint64

`Deprecated: Use the instruments provided by go.opentelemetry.io/otel/metric/instrument instead.`

The package should be updated to remove this deprecated dependency.

**Comment by giovanni-orciuolo** [comment]
For anyone stumbling upon the same issue, the solution at the moment would be to downgrade the package to version 0.34.0 by running the following command:

`go get go.opentelemetry.io/otel/metric@v0.34.0`

Which contains the old definitions.

**Comment by tdakkota** [comment]
Try the latest version. I've bumped `ogen` version, it uses new metric API.
