### ISSUE TITLE
Unable to install ogent using module path from blog post

### ISSUE THREAD

**Issue by tdakkota** [ariga/ogent#43]
I'd tried to install `ogent` as described in [Getting started section](https://entgo.io/blog/2022/02/15/generate-rest-crud-with-ent-and-ogen/#getting-started) of blog post.
```console
$ go get entgo.io/contrib/entoas@master ariga.io/ogent@master
go: downloading entgo.io/contrib v0.2.1-0.20220218155233-55ffdd80c70b
go get ariga.io/ogent@master: unrecognized import path "ariga.io/ogent": parse https://ariga.io/ogent?go-get=1: no go-import meta tags ()
```

But it seems module path is wrong, it should be `github.com/ariga/ogent@main`: 
```console
$ go get -v github.com/ariga/ogent@main  
go: downloading github.com/ariga/ogent v0.0.0-20220217081816-c4d586fc1c16
...
```

**Comment by masseelch** [comment]
Thanks @tdakkota. Fixed with https://github.com/ent/ent/pull/2357.
